"""added tag table

Revision ID: 343530abcce1
Revises: None
Create Date: 2013-06-06 20:31:25.769592

"""

# revision identifiers, used by Alembic.
revision = '343530abcce1'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    ### end Alembic commands ###
